// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "mrBAvatar":return img`
........................
...............ffff.....
...............f11f.....
....ffff.......f11f.....
....f11f.......f11f.....
....f11ffffffffffff.....
....f11feeef333f........
....fff333ef3f3efffff...
ffffffe3f3ef333eff11f...
f111ffe333efeeeeff11f...
f111ffeeeeefeeeeff11f...
f111ffeeeeefeeeefffff...
ffffffeeeeefeeeeef......
.....feeffffffeeef......
.....feeeeeeeeeeef......
......feeeeeeeeef.......
.......feeeeeeef........
........fffffff.........
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "can":return img`
. . . . . . . . . . . . . . . . 
. . . . f 6 . . . 6 f . . . . . 
. . . f 9 9 6 6 6 9 9 f . . . . 
. . f 9 9 9 9 9 9 9 9 9 f . . . 
. . f 9 9 9 9 9 9 9 9 9 f . . . 
. . f 9 9 f f f f f 9 9 f . . . 
. . f 9 f 2 2 f 1 1 f 9 f . . . 
. . f 9 f 2 f 1 1 1 f 9 f . . . 
. . f 9 f f 1 1 1 f f 9 f . . . 
. . f 9 f 1 f f f 8 f 9 f . . . 
. . f 9 f f 8 8 8 8 f 9 f . . . 
. . f 9 9 f f f f f 9 9 f . . . 
. . f 9 1 1 . 1 . 1 1 1 f . . . 
. . f 9 1 . 1 1 . 1 1 1 f . . . 
. . f 9 1 1 . 1 . 1 . . f . . . 
. . . 6 6 6 6 6 6 6 6 6 . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
